### PR TITLE
Tests refactoring

### LINKED ISSUE #22: Occasionally tests fail
Since some of the checks run after a timeout (at the moment 1000ms) after a request is started, we cannot be sure the request was completed, and the test may fail.
This happens a few times, but it shouldn't.

### PR DESCRIPTION
**Pull request by leogr**
I will squash commit and add "(fixes #22)" to the message

### CODE REVIEW

**Review by theboolean — APPROVED** [review]

File: test/unit/client/Client.js [hunk 1]
```diff
@@ -219,6 +219,32 @@ describe("Proauth client", function () {
         done()
       })
     })
-})
+  })
+
+  it("doesn't not refresh tokens concurrently", function (done) {
```
Comment (theboolean) [inline test/unit/client/Client.js]: @leogr typo

**Review by leodido — APPROVED** [review]

File: test/unit/client/Client.js (hunk 1 above)
Comment (leogr) [reply test/unit/client/Client.js]: fixed!
